// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package lexer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LEFT_PAREN-0]
	_ = x[RIGHT_PAREN-1]
	_ = x[LEFT_BRACE-2]
	_ = x[RIGHT_BRACE-3]
	_ = x[DOT-4]
	_ = x[MINUS-5]
	_ = x[PLUS-6]
	_ = x[SEMICOLON-7]
	_ = x[SLASH-8]
	_ = x[STAR-9]
	_ = x[BANG-10]
	_ = x[BANG_EQUAL-11]
	_ = x[EQUAL-12]
	_ = x[EQUAL_EQUAL-13]
	_ = x[GREATER-14]
	_ = x[GREATER_EQUAL-15]
	_ = x[LESS-16]
	_ = x[LESS_EQUAL-17]
	_ = x[IDENTIFIER-18]
	_ = x[STRING-19]
	_ = x[NUMBER_INT-20]
	_ = x[NUMBER_FLOAT-21]
	_ = x[PROVIDER-22]
	_ = x[EOF-23]
}

const _TokenType_name = "LEFT_PARENRIGHT_PARENLEFT_BRACERIGHT_BRACEDOTMINUSPLUSSEMICOLONSLASHSTARBANGBANG_EQUALEQUALEQUAL_EQUALGREATERGREATER_EQUALLESSLESS_EQUALIDENTIFIERSTRINGNUMBER_INTNUMBER_FLOATPROVIDEREOF"

var _TokenType_index = [...]uint8{0, 10, 21, 31, 42, 45, 50, 54, 63, 68, 72, 76, 86, 91, 102, 109, 122, 126, 136, 146, 152, 162, 174, 182, 185}

func (i TokenType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TokenType_index)-1 {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[idx]:_TokenType_index[idx+1]]
}
