// Code generated by "stringer -type=Type"; DO NOT EDIT.

package tokens

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LEFT_PAREN-0]
	_ = x[RIGHT_PAREN-1]
	_ = x[LEFT_BRACE-2]
	_ = x[RIGHT_BRACE-3]
	_ = x[LEFT_BRACKET-4]
	_ = x[RIGHT_BRACKET-5]
	_ = x[DOT-6]
	_ = x[MINUS-7]
	_ = x[PLUS-8]
	_ = x[SEMICOLON-9]
	_ = x[SLASH-10]
	_ = x[STAR-11]
	_ = x[COMMA-12]
	_ = x[BANG-13]
	_ = x[BANG_EQUAL-14]
	_ = x[EQUAL-15]
	_ = x[EQUAL_EQUAL-16]
	_ = x[GREATER-17]
	_ = x[GREATER_EQUAL-18]
	_ = x[LESS-19]
	_ = x[LESS_EQUAL-20]
	_ = x[IDENTIFIER-21]
	_ = x[STRING-22]
	_ = x[NUMBER_INT-23]
	_ = x[NUMBER_FLOAT-24]
	_ = x[TRUE-25]
	_ = x[FALSE-26]
	_ = x[PROVIDER-27]
	_ = x[RESOURCE-28]
	_ = x[AS-29]
	_ = x[LOOKUP-30]
	_ = x[VAR-31]
	_ = x[IS-32]
	_ = x[OUTPUT-33]
	_ = x[EOF-34]
}

const _Type_name = "LEFT_PARENRIGHT_PARENLEFT_BRACERIGHT_BRACELEFT_BRACKETRIGHT_BRACKETDOTMINUSPLUSSEMICOLONSLASHSTARCOMMABANGBANG_EQUALEQUALEQUAL_EQUALGREATERGREATER_EQUALLESSLESS_EQUALIDENTIFIERSTRINGNUMBER_INTNUMBER_FLOATTRUEFALSEPROVIDERRESOURCEASLOOKUPVARISOUTPUTEOF"

var _Type_index = [...]uint8{0, 10, 21, 31, 42, 54, 67, 70, 75, 79, 88, 93, 97, 102, 106, 116, 121, 132, 139, 152, 156, 166, 176, 182, 192, 204, 208, 213, 221, 229, 231, 237, 240, 242, 248, 251}

func (i Type) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Type_index)-1 {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[idx]:_Type_index[idx+1]]
}
